POST http://localhost:3001/archivefilesR2B HTTP/1.1 
content-type: application/json

{
    "fileName": "blackdoh1_test1"
}
###
POST http://localhost:3001/archivefilesR2B/filter HTTP/1.1 
content-type: application/json

{
  "startDate": "2020-12-07 00:00:00",
  "endDate": "2021-03-26 23:59:59",
  "worldContents": [
    "Prat-PreProd",
    "Prat-Prod"
  ],
  "subSystems": [
    "דוח 1" 
  ]
}
###
POST http://localhost:3001/archivefilesR2B/content HTTP/1.1 
content-type: application/json

{
  "guid": "2f3ca8b9-7235-4b7d-b4ca-f5b754b54c80"
}
###
POST http://localhost:3001/archivefilesR2B/updateFileStatus HTTP/1.1 
content-type: application/json

{
  "guid": "2f3ca8b9-7235-4b7d-b4ca-f5b754b54c80"
}
